// <auto-generated />
using System;
using DannyDefaults.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DannyDefaults.Migrations
{
    [DbContext(typeof(Default_Context))]
    [Migration("20240401153006_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DannyDefaults.Models.Default_Model", b =>
                {
                    b.Property<int>("DefaultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DefaultId"));

                    b.Property<DateTime>("DefaultDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DefaultInt")
                        .HasColumnType("int");

                    b.Property<string>("DefaultLetter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DefaultId");

                    b.ToTable("Defaults_table");
                });
#pragma warning restore 612, 618
        }
    }
}
